### ISSUE TITLE
Pretty print of Tensor

### ISSUE THREAD

**Issue by nathanielsimard** [burn-rs/burn#138]
### Feature description

Implement `std::fmt::Display` for `Tensor` and `BoolTensor` the same way for each `Backend` with basic metadata.
This could look something like the following, but it's just a draft.

```
Tensor {
  data: [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],
  shape:   [30, 30],
  device:  Cpu,
  backend: ndarray,
  dtype:   f32,
}
 ```

**Comment by nopestack** [comment]
Is anyone already looking into this issue? If not I'd be happy to contribute.

**Comment by nathanielsimard** [comment]
I don't know anyone who is working on this, so feel free to contribute.

**Comment by nopestack** [comment]
@nathanielsimard what's the best place to put a test for this feature?

**Comment by nopestack** [comment]
@nathanielsimard I've started working on https://github.com/burn-rs/burn/pull/146

I'd appreciate if you can point me to the right direction there.

**Comment by nathanielsimard** [comment]
@nopestack I just replied in the draft pull request, the test is at the right place.

To display the data (values) we should use the `std::fmt::Display` implementation of the `Data` struct using the `to_string` method.
It's already implemented, but the output is just wrong. The refined implementation can be done in another pull request to reduce the scope.

**Comment by sunny-g** [comment]
Took a stab [here](https://github.com/procyon-rs/showata/pull/29) to add [showata](https://github.com/procyon-rs/showata) support for `burn-tensor` for use in Jupyter; would be willing to collab! 

here's the current output which is likely too simple rn, but I'm quite new to ML/torch so 🤷 
![Screenshot 2023-03-11 at 12 40 55](https://user-images.githubusercontent.com/2055636/224505974-8bb519c6-1f5d-4607-af93-155beb5811f3.png)

**Comment by nathanielsimard** [comment]
That's a good start! I think it's probably a good idea to start by implementing `core::fmt::Display` for the `Data` struct. I would be happy to review your work if you want to open a PR.

I'm not sure how we can generalize the function to any number of dimensions, but maybe a recursive strategy would work, since we only want to print nested 2D matrices after all.

**Comment by antimora** [comment]
@agelas , @nathanielsimard This task is done, correct? If so, please close it.
