### ISSUE TITLE
Feature request: Mish activator

### ISSUE THREAD

**Issue by bioinformatist** [burn-rs/burn#159]
### Feature description

Hey, can I implement the [Mish activator](https://arxiv.org/abs/1908.08681) (of course as well as its unit test) for burn?

### Feature motivation

It does have better performance in our projects (implemented by Tensorflow in the past).

### (Optional) Suggest a Solution

I wanna do this job myself. Could I:smile:?

**Comment by nathanielsimard** [comment]
Yes, go ahead, if you need help or anything just ask on the discord.
