### ISSUE TITLE
Make inference packages no_std compatible for ndarray backend

### ISSUE THREAD

**Issue by antimora** [burn-rs/burn#168]
### Feature description

`burn-core`, `burn-tensor`, and `burn-ndarray` should run with `no_std` attribute. 

### Feature motivation

Making inference packages (burn-core, burn-tensor, and burn-ndarray) `no_std` compatible gives developers ability to deploy models for inference mode to wasm, embedded systems and mobile (or any other system where OS might not be available. 

### (Optional) Suggest a Solution

General steps on how are outlined in this book's chapter on no_std: https://www.lurklurk.org/effective-rust/no-std.html. 

Specific steps on the current solution will be updated here (TBD).

**Comment by antimora** [comment]
Completed the task. Closing as done.

**Comment by antimora** [comment]
@spadarian, I worked on this PR to make Burn (deep learning framework) no_std compatible. Take a look: https://github.com/burn-rs/burn.

There is a section on no_std: https://github.com/burn-rs/burn#no_std-support

Here is an online demo that relies on no_std and it compiles with wasm: https://burn-rs.github.io/demo

We have CIs that test no_std, so we know Burn builds for no_std. 

For the inference, you'll need to use burn-ndarray backend. I am currently working on ONNX import part: https://github.com/burn-rs/burn/issues/204 but it will be a while to have the full set of ops.

**Comment by spadarian** [comment]
I checked the no_std example... I still get a bunch of errors like this one (all relates to `spin`):

```bash
error[E0599]: no method named `compare_exchange_weak` found for struct `AtomicBool` in the current scope
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spin-0.9.8/src/mutex/spin.rs:182:14
    |
180 |           while self
    |  _______________-
181 | |             .lock
182 | |             .compare_exchange_weak(false, true, Ordering::Acquire, Ordering::Relaxed)
    | |             -^^^^^^^^^^^^^^^^^^^^^ method not found in `AtomicBool`
    | |_____________|
```

Maybe there is something wrong with my configuration?

**Comment by antimora** [comment]
Yeah, I have seen this before. AtomicBool is not available for the older ARM but works for `thumbv7m-none-eabi`. Atomic CPU feature is needed for locking. Can you share which target you're attempting to build?

**Comment by spadarian** [comment]
It's for the rp2040... so I think it is `thumbv6m-none-eabi`

**Comment by antimora** [comment]
@spadarian Go ahead file a ticket if there is no workaround, we can remove the dependency on the lock. It was used for multithreaded environment but I think we can relay for such embedded device.
