### ISSUE TITLE
Add test coverage report to identify test gaps

### ISSUE THREAD

**Issue by antimora** [burn-rs/burn#174]
### Feature description

As part of CI build we should generate [Source-based Code Coverage](https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#source-based-code-coverage) report. 

### Feature motivation

This is a great way to see if tests are missing for added code. This also will encourage more testing. 

### (Optional) Suggest a Solution

Use [Source-based Code Coverage](https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#source-based-code-coverage). Also there is GitHub action that could be used to read coverage reports: https://github.com/marketplace/actions/code-coverage-summary.   

Example how a coverage is reported: https://github.com/bincode-org/bincode/pull/619#issuecomment-1436265634

**Comment by antimora** [comment]
Another example: https://github.com/gabotechs/dynarust/blob/main/.github/workflows/test-lint.yml

**Comment by louisfd** [comment]
Done in #902 thanks @Luni-4
