### ISSUE TITLE
Burn deserves its own book

### ISSUE THREAD

**Issue by antimora** [burn-rs/burn#200]
I believe Burn is more than a library or framework and it deserves documentation in the style of book, like Rust (https://doc.rust-lang.org/book/) or Serde (https://serde.rs/).

I would like to see these topic to be included:

1. Introduction and motivation (pretty much from the first blog post: https://burn-rs.github.io/blog/a-case-for-rust-in-deep-learning)
2. Overall design and concepts. 
3. Design goals and tenets for the project (kinda a promise what burn will be or evolve, similar to Rust's zero cost abstraction)
4. Explanation of components (training, datasets , etc). 
5. Examples (training, inference, etc).
6. Contributing, like how would I add a new backend or new tensor operations.
7. Future road maps. 

I am sure there are more but I really would love to dive in and read this book.

**Comment by wdoppenberg** [comment]
I tried to make a small setup for a book; it's far from complete. Let me know what you think:

```md
[Overview](../../README.md)

[Motivation](./motivation.md)

[Installation](./installation.md)

- [Usage](./usage/README.md)
  - [Quick Start](./usage/quick-start.md)
- [Concepts](./concepts/README.md)
  - [Tensors](./concepts/tensors.md)
  - [Backend](./concepts/backend.md)
  - [Configs](./concepts/configs.md)
  - [Datasets](./concepts/datasets.md)
  - [Models](./concepts/models.md)
  - [Metrics](./concepts/metrics.md)
  - [Losses](./concepts/losses.md)
  - [Optimizers](./concepts/optimizers.md)
  - [Advanced](./concepts/advanced/README.md)
    - [Records](./concepts/advanced/records.md)
    - [Macros](./concepts/advanced/macros.md)

[Zero to LLaMA2](./zero-to-llama2.md)

[Help](./help.md)

[Contributing](./contributing.md)
```

**Comment by antimora** [comment]
Linking the follow up PR: https://github.com/burn-rs/burn/pull/632

Update: we have the first draft with guide section. Please check out it. It's on main. To view run this:

1. `cargo install mdbook`
2. Then in burn-book: `mdbook serve`

Then it should be at http://localhost:3000/

We will put it somewhere online some time soon

**Comment by antimora** [comment]
Thanks everyone (@wdoppenberg , @louisfd , @nathanielsimard ) for launching Burn's own book. Many would very appreciate this! 

Here is the link again to the book: https://burn-rs.github.io/book/

We will probably have another book on Development Guide that will have Design, Tenets, etc, so that we can refer to when adding new features, and it'd be very useful for new contributors.

Closing as complete.
