### ISSUE TITLE
Training plots are not clear

### ISSUE THREAD

**Issue by antimora** [burn-rs/burn#211]
**Describe the bug**

The plots are not clear and have too many dots.

**To Reproduce**
Run training of `examples/mnist`

**Expected behavior**
It would be if a different markers are used to plot. 

**Screenshots**
![image](https://user-images.githubusercontent.com/939125/223562702-395ad97c-e259-4a0a-b90b-834ca9af41e1.png)

**Desktop (please complete the following information):**
```
[~]$ uname -a
Darwin MacBook-Pro.local 22.3.0 Darwin Kernel Version 22.3.0: 
Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64
[~]$ 
```

**Comment by antimora** [comment]
Hi @NicBonetto , welcome to the project. 

This has not been resolved. Your contribution is highly appreciated. 

I filed this ticket originally. I thought the training charts are not that clear and could be improved.

@nathanielsimard and I are here to review your changes or can talk on discord to ask for help.

**Comment by nathanielsimard** [comment]
@NicBonetto Don't be afraid to come talk on Discord about how you want to tackle the issue; we can help. :)

**Comment by antimora** [comment]
I think we should replace the `textplot` with [termplot](https://github.com/xavierhamel/termplot) library because `textplot` is not updated anymore and uses `nom` version 1 which gives a warning when building burn.

**Comment by NicBonetto** [comment]
I've just started to play around with the examples, and may need some help with initial setup. Is this a good place to ask or should we move the discussions over to discord? (sorry in advanced if these are stupid questions).

**Comment by antimora** [comment]
> I've just started to play around with the examples, and may need some help with initial setup. Is this a good place to ask or should we move the discussions over to discord? (sorry in advanced if these are stupid questions).

Please do not worry about asking questions. We are all learning here and often we are not sure either. 

I would recommend to try discord for back and worth questions/answers. We are all on it and it's not busy over there. 

But I would suggest you keep updating the ticket to have a record of the discussion and new findings. It will help others learn as well.

**Comment by nathanielsimard** [comment]
I think we should replace the current implementation with something like ratatui https://github.com/ratatui-org/ratatui. It would be better than the actual implementation and seems much more maintained, potentially avoiding security vulnerabilities.
