### ISSUE TITLE
New burn-wgpu backend

### ISSUE THREAD

**Issue by antimora** [burn-rs/burn#243]
### Feature description

The new upcoming GPU API standard [WebGPU](https://en.wikipedia.org/wiki/WebGPU) is being finalized and available for use. The single API makes possible to access compute/graphical capabilities of various GPU cards. The API is also being standardize and available on browsers. 

 The [WGPU](https://wgpu.rs/) is WebGPU implementation in Rust. Here are its features:

> wgpu is a safe and portable graphics library for Rust based on the WebGPU API. It is suitable for general purpose graphics and compute on the GPU.
> 
> Applications using wgpu run natively on Vulkan, Metal, DirectX 11/12, and OpenGL ES; and browsers via WebAssembly on WebGPU and WebGL2.

### Feature motivation

It would be a great addition to Burn's backend family. wgpu backend will enable acceleration on machines without needing to install addition binaries to access GPU power. 

### (Optional) Suggest a Solution

[WONNX](https://github.com/webonnx/wonnx) project already did a heavy lifting and writing code all needed operators for burn's backend. So we need to port them for `burn`.

**Comment by antimora** [comment]
Pinged WONNX team to clarify their license. It seems it's a dual license as burn's (said in the cargo.toml file).

**Comment by antimora** [comment]
Implementation status page of WebGPU: https://github.com/gpuweb/gpuweb/wiki/Implementation-Status

**Comment by antimora** [comment]
Found an [interesting example of wgpu](https://github.com/simbleau/nbody-wasm-sim) usage with webgl feature flag: https://github.com/simbleau/nbody-wasm-sim/blob/main/Cargo.toml#L30. This is useful for web cases when WebGPU is not available in a browser (currently only select browsers have access to WebGPU). Probably wgpu translates `wgsl` to `glsl` behind the scene.

It seems wgpu can t

**Comment by antimora** [comment]
WebGPU is available on Chrome: https://developer.chrome.com/blog/webgpu-release/

Someone run some benchmark: https://github.com/FL33TW00D/wgpu-mm

**Comment by antimora** [comment]
Good documentation on wgpu: https://sotrh.github.io/learn-wgpu/

**Comment by antimora** [comment]
Related and interested project: https://lib.rs/crates/custos

**Comment by antimora** [comment]
https://webgpufundamentals.org/

WebGPU fundamentals

**Comment by antimora** [comment]
https://github.com/mlc-ai/web-llm

**Comment by ksf** [comment]
As in #287 the issue of kernels for OpenCL was raised, [I'd like to point into the general direction of arrayfire](https://github.com/arrayfire/arrayfire/tree/master/src/backend/opencl/kernel), 3-clause BSD. It's a C++ project but the CL kernels, are, well, CL. 

While wgpu definitely is more portable OpenCL has some memory addressing features and also semantic guarantees (precision and the like) that just aren't present in graphics-centered APIs. Whether that's an issue probably depends more on what people want to do with burn than burn itself.

OpenCL availability should also be decent, at least under linux, especially when mesa 23.1 releases (it's almost done), promoting rusticl from an experimental to stable feature. Nvidia and AMD don't give OpenCL much love, Apple right-out axed it, but it's also far from dead.

**Comment by nathanielsimard** [comment]
Thanks for the insight, it's good to know. WebGPU is good for portability by being compiled to wasm but it may not be the best option to provide the fastest backend. OpenCL is normaly slower on Nvidia devices, so maybe the best option is not to aim for a single backend that compiles to every platform, but providing multiple backends more specialized for each platform.

**Comment by antimora** [comment]
@nathanielsimard has the first PR for the backend: https://github.com/burn-rs/burn/pull/376

(if anyone is interested reviewing it)

**Comment by antimora** [comment]
One way you can gauge completion is by searching todo for missing OP implementations in burn-wgpu like this: https://github.com/search?q=repo%3Aburn-rs%2Fburn%20burn-wgpu%20todo&type=code

**Comment by antimora** [comment]
OK. A working first version of burn-wgpu (v0.8.0) has been released thanks to @nathanielsimard and @louisfd 

https://github.com/burn-rs/burn/releases/tag/v0.8.0
