### ISSUE TITLE
Config -> HParams

### ISSUE THREAD

**Issue by nathanielsimard** [burn-rs/burn#251]
I'm thinking of renaming `Config` to `HParams` to better communicate its intention. We could also move the current `Config` derive to a proc macros:

```rust
#[derive(Config)]
struct LinearConfig {
...
}

#[hparams(module = "Linear")]
struct LinearHParams {
...
}

fn main() {
    let linear  = LinearConfig::new(5, 5).with_bias(false).init(); // Now
    let linear = Linear::config(5, 5).with_bias(false).init(); // Without the renaming
    let linear = Linear::hparams(5, 5).with_bias(false).init(); // New
}
```

To be honest I'm not sure which on is better and I'm open to sugestions!

**Comment by antimora** [comment]
The APIs are getting better.

Regarding renaming to HParams. I think the hyper parameters may go a level up, to the model level. 

Here are the possible alternative choises (I have no preference either):

1. Attributes (used by ONNX and probably conveys the idea of belonging to the op).
2. Settings (but it feels higher level)
3. Config (you already have it)

Maybe, renaming to Attributes?

**Comment by nathanielsimard** [comment]
Good propositions, I think config can go to the top level model via composition, that's what I was aiming for. So a transformer config can have a transformer encoder config that has an attention config that has a linear config and so on.

Maybe `HParams` is to contraining in scope, `Attributes` is more general and might be a more suitable name. I think I prefer it over config, settings or hparams for now.

**Comment by nathanielsimard** [comment]
At the top level, it could look like this:

```rust
#[attributes(type = "Experiment")]
struct ExperimentAttributes {
    model: ModelAttributes,
    optim: OptimAttributes,
    data: DataAttributes
}

struct Experiment {
    model: Model,
    optim: Optim,
    data: Data
}


fn main() {
    let experiment = Experiment::attrs(...).create();
}
```

I'm still unsure if we should use `Attrs` and the function `attrs` or the full name for both. Since it's going to be used often, using the shortest name might be the most Rusty thing to do.

**Comment by antimora** [comment]
@nathanielsimard do we have a conclusion on this ticket? It might a good time to resolve it since you're doing related work in this area.

**Comment by nathanielsimard** [comment]
I tried using Attributes, but it was more confusing than helpful, attributes is the term used for proc macro annotations in Rust. So I'm keeping config for now.

**Comment by antimora** [comment]
@nathanielsimard I guess for now, we will keep the naming the same. We tried a few things and we're back to the original naming. I'll close this ticket and let the users try out the new API improvements you've made in the upcoming release.
