### ISSUE TITLE
text-classification-db-pedia Error while text-classification-ag-news OK

### ISSUE THREAD

**Issue by ycat3** [burn-rs/burn#253]
**Describe the bug**
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `title`", line: 1, column: 263)', /home/mycat/projects/burn/burn-dataset/src/dataset/in_memory.rs:40:69

**To Reproduce**
cargo run --example text-classification-db-pedia --release

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04

**Additional context**
cargo run --example text-classification-ag-news --release
Successfully generate model.bin

**Comment by nathanielsimard** [comment]
Thanks for the bug report, since both `text-classification-db-pedia` and `text-generation` downloads `db-pedia` dataset, but requires different fields, there was a clash where the cache of the dataset version used for `text-generation` was also used for `text-classification`.
