### ISSUE TITLE
How to inference text-classification and text-generation

### ISSUE THREAD

**Issue by ycat3** [burn-rs/burn#254]
How to inference text-classification and text-generation by generated model.bin ?

**Comment by antimora** [comment]
We have an [inference example MNIST in WASM ](https://github.com/burn-rs/burn/tree/main/examples/mnist-inference-web) but you can modify to fit your needs. 

We have a ticket to get an inference example: https://github.com/burn-rs/burn/issues/165 If you have something working and you feel you can contribute, please submit a PR.
