### ISSUE TITLE
Add AdaptiveAvgPooling

### ISSUE THREAD

**Issue by VanderBieu** [burn-rs/burn#317]
I was trying to implement ResNet with master branch of Burn, but I found there is no implementation of AvgPooling or AdaptiveAvgPooling.

**Comment by antimora** [comment]
We have a ticket for MeanPool2D https://github.com/burn-rs/burn/issues/135. We could treat this a feature request for AdaptiveAvgPooling

**Comment by antimora** [comment]
We now have AvgPool and AdaptiveAvgPool (https://github.com/burn-rs/burn/pull/585, https://github.com/burn-rs/burn/pull/572) thanks to @nathanielsimard
