### ISSUE TITLE
ONNX: Implement shape inference for Identity

### ISSUE THREAD

**Issue by sajattack** [burn-rs/burn#331]
Re: #322 
### Feature description

http://www.xavierdupre.fr/app/mlprodict/helpsphinx/onnxops/onnx__Identity.html

### Feature motivation

Loading [this model](https://huggingface.co/NaruseMioShirakana/MoeSS-SUBModel/blob/main/hubert4.0.7z)
results in 
```
  thread 'main' panicked at 'not yet implemented: shape inference for Identity is not implemented', burn-import/src/onnx/shape_inference.rs:32:18
```
(after some hacking of the code to get to the root of the error rather than panicking with a more useless error message)

**Comment by maekawatoshiki** [comment]
I'm interested in implementing this.
(By the way, `onnxsim` would remove `Identity` op.)
