### ISSUE TITLE
ONNX: Implement Conv1D node type

### ISSUE THREAD

**Issue by sajattack** [burn-rs/burn#332]
Re: #322 
### Feature description
http://www.xavierdupre.fr/app/mlprodict/helpsphinx/onnxops/onnx__Conv.html

### Feature motivation
Loading https://huggingface.co/NaruseMioShirakana/MoeSS-SUBModel/blob/main/hubert4.0.7z
results in
```
thread 'main' panicked at 'not yet implemented: Node type not implemented: Conv1d', burn-import/src/onnx/to_burn.rs:580:21
```
after some hacking to get the error messages to be helpful

**Comment by antimora** [comment]
Fixed by https://github.com/burn-rs/burn/pull/638 PR
