### ISSUE TITLE
Sqlite feature flag needed

### ISSUE THREAD

**Issue by paulirotta** [burn-rs/burn#365]
**Describe the bug**
sqlite features cause cross-compiling builds to fail, even when not using sqlite

**To Reproduce**
There are different cross-compilation scenarios, but one is:
1. Create an Android app with NDK

2. Build Rust from Android, for example
```
apply plugin: 'org.mozilla.rust-android-gradle.rust-android'

cargo {
    verbose = true
    prebuiltToolchains = true
    profile = 'release'
    module = "../../mypackage"   // Directory for Rust
    libname = "mypackage"        // Cargo.toml's [package] name.
    targets = ["arm", "arm64", "x86", "x86_64"]
}

tasks.whenTaskAdded { task ->
    if ((task.name == 'javaPreCompileDebug' || task.name == 'javaPreCompileRelease')) {
        task.dependsOn 'cargoBuild'
    }
}

task nativeLibsToJar(type: Copy, description: 'create a jar archive of the native libs') {
    from fileTree(dir: 'libs', include: '**/*.so')
    into 'lib/'
    destinationDir file("$buildDir/native-libs")
}
```

3. Include burn as a dependency in the Rust NDK library bundled in the app

**Expected behavior**
Clean build without need for unused sqlite dependency setup. This also applies without cross-compilation since at the time of writing sqlite is not feature gated.

**Desktop (please complete the following information):**
 - OS: Linux Mint, Intel

**Smartphone (please complete the following information):**
 - Device: targets = ["arm", "arm64", "x86", "x86_64"]
 - OS: [Android, iOS]

**Comment by paulirotta** [comment]
The current workaround is.
1. On development manchine, install sqlite3-dev

2. In the application `Cargo.toml`, add the following:
`[dependencies]
rusqlite = {version = "0.29", features = ["bundled-full"]}
`

**Comment by antimora** [comment]
"""
@paulirotta Thanks for reporting this. I am currently working on this area. We should certainly be able to fix it quickly.

In Burn-Dataset, Sqlite is replacing the JSON file as the storage mechanism. This makes it a core mechanism, and we can't make it optional behind the sqlite flag. However, we can use sqlite with `bundled-full`, which might help avoid future build problems, including those on Windows, similar to how Python bundles sqlite. The compilation doesn't seem to slow down. 

I should have it fixed soon, so you'll be able to try out the solution.  

Also, I'm curious, do you include Burn as a dependency in Android for inference only on Android? If so, we would recommend turning off the default features like this:

```toml
burn = {path = "../burn", version = "0.8.0", default-features = false}
burn-ndarray = {path = "../burn-ndarray", version = "0.8.0", default-features = false} # if you're using NDArray
```

You probably don't need Burn's training-related crates (burn-dataset is for training purposes). 

Here's an example crate with all defaults set for inference: https://github.com/burn-rs/burn/blob/main/burn-no-std-tests/Cargo.toml . This tests no-std, but it's applicable. 
"""

**Comment by paulirotta** [comment]
Perfect. I'll validate after the fix is up.

Yes, ndarray inference for now. On-phone training as the use case develops. I'm looking forward to the other backends that may be ripe in coming months but that is not a concern any time soon. I'll help as time+skill permits.

**Comment by antimora** [comment]
> Perfect. I'll validate after the fix is up.
> 
> Yes, ndarray inference for now. On-phone training as the use case develops. I'm looking forward to the other backends that may be ripe in coming months but that is not a concern any time soon. I'll help as time+skill permits.

If it's only inference, I would recommend using `default-features = false` for these two crates. You'll save build time this way. 

I submitted a PR, once approved and merged, you can try out again. 

CCing @nathanielsimard, so he's aware of your use case. We have plans for WebGPU backend (#243). In the future, it'd be possible to speedup computation via Android Vulkan support (see https://github.com/gfx-rs/wgpu support matix)

**Comment by antimora** [comment]
@paulirotta The fix has been merged. Let us know if this helped you.

**Comment by paulirotta** [comment]
Perfect. Fix confirmed on M1 mac and Intel Linux Mint
