### ISSUE TITLE
Add Xavier/Glorot initializer

### ISSUE THREAD

**Issue by antimora** [burn-rs/burn#371]
Requesting to add Xavier/Glorot initializer which is commonly used and needed for LSTM.

**Comment by agelas** [comment]
Whoever works on this feature, please update the LSTMConfig in `burn-core/src/nn/lstm/lstm.rs` to use Xavier initialization by default (line 26).

**Comment by louisfd** [comment]
I'll do it

**Comment by antimora** [comment]
@louisfd is it safe to close this ticket since your PR has been closed?

**Comment by antimora** [comment]
Closing as done via: https://github.com/burn-rs/burn/pull/394

@louisfd Thank you!
