### ISSUE TITLE
Burn development and community

### ISSUE THREAD

**Issue by ujjwalnur** [burn-rs/burn#383]
I'd like to actively would work and collaborate for the development of burn.

There is an architectural document which I have gone through. However I'd still like some inputs over a few issues

1. **Roadmap**: Is there a plan or a roadmap towards upcoming releases? It'd be great to have it as I can then focus over specific parts of the project.
2. **Community**: Is there a community forum or even a  social media handle to enable better outreach including discussions and feedback with users ?

**Comment by antimora** [comment]
Hey there, welcome to Burn! We're happy to have more folks on board. 

Just to let you know, we've got a discord server where all the magic happens: https://discord.gg/uPEBbYYDB6 (you can spot this link in the main Readme file).

We don't exactly have a formal roadmap, but we chat about our plans and ideas on the discord. @nathanielsimard and I often toss our plans back and forth there, too. Maybe it's about time we started sharing them, huh? Here's a quick rundown of what we're cooking up for this release (and @nathanielsimard, feel free to jump in if I get something wrong):

1. (@nathanielsimard) Reworking `burn-import` to make it easier to implement ONNX ops.
2. (Me, @antimora) Upgrading `burn-dataset` to use sqlite for storing datasets (this includes those from HuggingFace and user datasets).
3. (@nathanielsimard) A new backend for Burn called `burn-wgpu` (WebGPU).
4. (@nathanielsimard and me, @antimora) Working on implementing ONNX ops needed to import BERT trained models.
5. (Me, @antimora) Implement burn-report for Training Progress Reporting to CometML and Other Dashboards.

@agelas and @bioinformatist have been very active and submitting PRs on their own. 


That's about it. Thanks again for joining us, and let's make some cool stuff together!

**Comment by bioinformatist** [comment]
@ujjwalnur Welcome!
