### ISSUE TITLE
MPT-7B Example with fine tuning.

### ISSUE THREAD

**Issue by ianpurton** [burn-rs/burn#400]
### Feature description

A working example of the burn-rs code to run and fine tune a large language model. For example https://www.mosaicml.com/blog/mpt-7b

### Feature motivation

The space for fine tuning LLM's on private data is very immature at the moment. 

Mostly you get pointed to a Jupyter notebook running on one of the cloud providers. This is no good for corporates that can't upload data to the cloud.

For example Mosaic have a docker container to fine tune their own MPT-7b but it's currently not working https://github.com/mosaicml/llm-foundry/issues/316

To fine tune LLM's on private corporate data I can't find anything that I could reliably put into production.

It would be great to have a Rust solution and I think it would showcase burn-rs.

**Comment by antimora** [comment]
We do have plans for hosting examples of popular models with Burn. However, it'll be a separate project and not under burn but with burn-rs org. @nathanielsimard can tell on this more. Currently our efforts are focussed on making `burn-import` complete, which is a requirement for importing third party models.

**Comment by HHogg** [comment]
@antimora Just wondering how this is going? I'm interested in seeing an example of fine tuning an open source model too.

**Comment by antimora** [comment]
@laggui i think we've got a fine tuning working somewhere, correct?

**Comment by laggui** [comment]
> @laggui i think we've got a fine tuning working somewhere, correct?

We have a fine-tuning example for ResNet on the [models repo](https://github.com/tracel-ai/models/tree/main/resnet-burn#fine-tuning).

Regarding LLM fine-tuning, no official example yet.
