### ISSUE TITLE
Operation `Tensor::index_select_dim_assign` inconsistent between ndarray and tch backends on Tensors of dimensions > 2.

### ISSUE THREAD

**Issue by cookiemon** [burn-rs/burn#438]
**Describe the bug**
The ndarray backend and the tch backend disagree on how the `Tensor::index_select_dim_assign` operation is implemented.

**To Reproduce**
Below a code snipped that showcases the behavior (also how I'd expect the operation to work). To run it, generate a small project that depends on burn-rs. The function test will trigger an assertion inside `index_select_dim_assign` when running with the ndarray backend, and runs through successfully with tch backend. Superficially it seems like they disagree in which dimension the selected indices belong but I haven't looked deeper into it.

```rs
use burn::tensor::backend::Backend;
use burn::tensor::{Data, Int, Tensor};
use burn_ndarray::NdArrayBackend;
use burn_tch::TchBackend;

fn test<B: Backend<FloatElem = f32, IntElem = i64>>() {
    let t = Tensor::<B, 2>::zeros([3, 4]);
    let idxs = Tensor::<B, 1, Int>::from_data([1, 2]);
    let v = Tensor::<B, 2>::from_data([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]]);
    t.index_select_dim_assign(1, idxs, v) // <- Assert is triggered inside this cal, the assert below is just what I'd expect as return value
        .into_data()
        .assert_approx_eq(
            &Data::from([
                [0.0, 1.0, 2.0, 0.0],
                [0.0, 3.0, 4.0, 0.0],
                [0.0, 5.0, 6.0, 0.0],
            ]),
            4,
        );
    println!("success");
}

fn main() {
    println!("===== tch backend =====");
    // This call runs through succesfully
    test::<TchBackend<f32>>();
    println!("===== nd-array backend =====");
    // This call fails inside Tensor::index_select_dim_assign from an assertion
    test::<NdArrayBackend<f32>>();
}
```

**Expected behavior**
I'd expect both backends to agree on the behavior.

**Comment by nathanielsimard** [comment]
Thanks @cookiemon for repporting the issue, I fix it in this [PR](https://github.com/burn-rs/burn/pull/441).

**Comment by antimora** [comment]
Fixed by the merged PR. Please reopen if you face the same issue. Thank you.

**Comment by antimora** [comment]
Fixed by the merged PR. Please reopen if you face the same issue. Thank you.
