### ISSUE TITLE
tch backend interprets range argument of`Tensor::arange` as (start, count).

### ISSUE THREAD

**Issue by cookiemon** [burn-rs/burn#439]
**Describe the bug**
`Tensor::arange` on tch backend interprets the range argument as (start, count) instead of (start, end). e.g. `Tensor::arange(2..5)` returns a tensor with values `[2, 3, 4, 5, 6]` when it should be `[2, 3, 4]` instead.

**To Reproduce**
Code below triggers the behavior.

```rs
use burn::tensor::backend::Backend;
use burn::tensor::{Data, Int, Tensor};
use burn_tch::TchBackend;

fn test<B: Backend<FloatElem = f32, IntElem = i64>>() {
    let idxs = Tensor::<B, 1, Int>::arange(2..5);
    println!("{:#?}", idxs);
    // Expected tensor to be [2, 3, 4], actually is [2, 3, 4, 5, 6]
    assert_eq!(idxs.into_data(), Data::from([2, 3, 4]));
}

fn main() {
    println!("===== tch backend =====");
    test::<TchBackend<f32>>();
}
```

**Comment by nathanielsimard** [comment]
@cookiemon Thanks for reporting the issue, I fixed the `tch` backend in this [PR](https://github.com/burn-rs/burn/pull/440).
