### ISSUE TITLE
 Rename tensor index to slice

### ISSUE THREAD

**Issue by wbrickner** [burn-rs/burn#449]
### Feature description

Apologies if this exists already (and the short novel that follows), I surely couldn't find documentation of it.

I want the ability to create a slice of an existing tensor. 
This could either be by copy or by reference, I don't care. Ideally this would be by reference, even with the ability to mutate.

### Feature motivation

I need to be able to iterate over rows of a matrix, or matrices in a stack, etc.  These operations are simple to do in all the popular python ML packages, but not in Burn as far as I'm aware.  I propose a more general purpose API for tensor slicing.

### (Optional) Suggest a Solution

One cute way to do this would be to implement the traits
- `Index<[Range<usize>; 1]>`
- `Index<[Range<usize>; 2]>`
- `Index<[Range<usize>; 3]>`
- `Index<[Range<usize>; 4]>`

Depending on the const dimensionality `D` of the tensor.  The API should probably provide an opaque `Tensor<...>` back, which internally remembers the data which backs it and the range of elements it addresses along the axes.

So in my perfect world you could write something like:

```rust
let view_a = tensor[[1, .., 0..3]];
let view_b = tensor[[1, .., 3..index]];

let a: f32 = important_op(view_a);
let b: f32 = important_op(view_b);

view_b *= (a - b);
```

I don't know how Tensor is implemented, so creating im/mutable references to it could be nasty and require reference counting and maybe locking, but this overhead is *probably* no big deal from a perf / memory perspective if the correct design is chosen.  Instead of forcing an Arc/Mutex onto every user of `Tensor`, perhaps a better approach would be to make the lifetimes and mutability visible to the compiler, although this comes along with the mutable-immutable borrowing collision issue.

Using Arc/Mutex, a `Tensor` could be backed by a `Data`, with a reasonable compromise:

```rust
struct Tensor<B, const D: usize> {
  backing: Data<B, D>,
  /// ...
}

enum Data<B, const D: usize> { 
  Owned(/* B-dependent value */),
  Shared {
    tensor: Arc<Mutex</* B-dependent value */>>,
    addressed_range: [ Range<usize>; D ]
  }
}
```

Locking could be done more intelligently by locking based on the addressed elements, not the entire tensor. E.g. you can read from one half just fine while an operation to mutate another half is occurring.  I don't know exactly how this would actually work efficiently.

Being able to slice into a tensor and read or mutate only a subset of its elements is very valuable and a fundamental operation needed for any ML / tensor library, so looking into solidifying an approach to it now would be good.

Dealing with different backend API semantics will likely not be as pretty.

**Comment by nathanielsimard** [comment]
There is the `Tensor::index` method that does what you want. We are thinking of renaming it to slice since it is more inline witht what is done. The method only takes `Range<usize>` as input, so there are possible improvements there to simplify the syntax.

```rust
let [dim0, dim1, dim2] = tensor.dims();
let view_a = tensor.index([1..2, 0..dim1, 0..3]);
let view_b = tensor.index([1..2, 0..dim1, 3..dim2]);
```

**Comment by wbrickner** [comment]
This method takes ownership, so I can't create a slice so much as I can discard parts of a tensor, or do a massive clone and then discard it all - right?

**Comment by nathanielsimard** [comment]
The clones are never massive with burn, it's only increasing a reference to the tensor's data. When multiple references are pointing to the same tensor's data, the data is readonly. When there is only one reference, all operations that can be inplace will be inplace without having to specify it. All tensor operations take owned tensors for this reason, which helps a ton with memory usage.

**Comment by antimora** [comment]
I will leave this ticket as open and as an action is to rename `index` to `slice`. Also we should review if the feature of index matches what's been requested.

**Comment by antimora** [comment]
This related to https://github.com/burn-rs/burn/issues/426

**Comment by wbrickner** [comment]
Can we build Index implementations for these methods with integers, ranges, etc?

**Comment by nathanielsimard** [comment]
There are select, select _assign, gather and scatter to work with indices.

**Comment by wbrickner** [comment]
I think we miscommunicated, I mean the Index trait, so we can write very pretty things like `tensor[xyz]` (xyz is an int tensor) or `tensor[[x..y, a..b, y]]`.
