### ISSUE TITLE
Add time estimate to progress bar when training a model

### ISSUE THREAD

**Issue by nathanielsimard** [burn-rs/burn#454]
Why it was removed: https://github.com/burn-rs/burn/issues/447
When to add it back: https://github.com/console-rs/indicatif/issues/556

**Comment by teor2345** [comment]
The panic was already fixed in PR https://github.com/console-rs/indicatif/pull/555 , but that hasn't made it into a release yet.

Even with the panic fix, the estimates are still wrong, so that's what my ticket https://github.com/console-rs/indicatif/issues/556 is about.

**Comment by louisfd** [comment]
Closed, replaced by Ratatui
