### ISSUE TITLE
burn-tensor does not compile

### ISSUE THREAD

**Issue by temrix** [burn-rs/burn#476]
**Describe the bug**

I figured out that `burn-tensor` does not compile (017485b9ea411fd38e7421a579fcb3d2d7200cfc). I could narrow the problem down to being introduced in bd58922784cdbdc10675b318a56c7e5f42ffb99a. The error message is `(signal: 7, SIGBUS: access to undefined memory)`.

**To Reproduce**

```
git checkout bd58922784cdbdc10675b318a56c7e5f42ffb99a
cd burn-tensor/
cargo build
```

```
Compiling burn-tensor v0.6.0 (/home/temrix/Dokumente/Coding/MachineLearning/burn/burn-tensor)
error: could not compile `burn-tensor` (lib)

Caused by:
  process didn't exit successfully: `rustc --crate-name burn_tensor --edition=2021 burn-tensor/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=88 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=6ab9f965acd38970 -C extra-filename=-6ab9f965acd38970 --out-dir /home/temrix/Dokumente/Coding/MachineLearning/burn/target/debug/deps -C incremental=/home/temrix/Dokumente/Coding/MachineLearning/burn/target/debug/incremental -L dependency=/home/temrix/Dokumente/Coding/MachineLearning/burn/target/debug/deps --extern derive_new=/home/temrix/Dokumente/Coding/MachineLearning/burn/target/debug/deps/libderive_new-1e714c8bb5df9345.so --extern half=/home/temrix/Dokumente/Coding/MachineLearning/burn/target/debug/deps/libhalf-fb3f9c287b55cfa3.rmeta --extern hashbrown=/home/temrix/Dokumente/Coding/MachineLearning/burn/target/debug/deps/libhashbrown-14afb34d32240458.rmeta --extern libm=/home/temrix/Dokumente/Coding/MachineLearning/burn/target/debug/deps/liblibm-4529f95fe460a643.rmeta --extern num_traits=/home/temrix/Dokumente/Coding/MachineLearning/burn/target/debug/deps/libnum_traits-76557a49a7b225db.rmeta --extern rand=/home/temrix/Dokumente/Coding/MachineLearning/burn/target/debug/deps/librand-8f02bc213b284c94.rmeta --extern rand_distr=/home/temrix/Dokumente/Coding/MachineLearning/burn/target/debug/deps/librand_distr-c9cf08214addd80c.rmeta --extern serde=/home/temrix/Dokumente/Coding/MachineLearning/burn/target/debug/deps/libserde-437ed021fdd15433.rmeta` (signal: 7, SIGBUS: access to undefined memory)
```

**Expected behavior**

`burn-tensor` should compile successfully. 

**Desktop (please complete the following information):**
 - OS: Devuan 4 chimaera (like Debian 11 bullseye)
 - Browser N/A
 - Version commit bd58922784cdbdc10675b318a56c7e5f42ffb99a
 - rustc 1.70.0 (90c541806 2023-05-31)

**Comment by antimora** [comment]
It seems the cargo is failing to build properly. I haven't tried building on my end but can you please upgrade your tool chain to the latest with all patches up to date? Could you rebuild with cargo clean first? Also please make sure you're on rust stable.

**Comment by temrix** [comment]
It seems to be some weird environment issue on my end because in Docker on the same machine, everything works and the same on my laptop. Tool chain is `stable-x86_64-unknown-linux-gnu` (the latest at the moment) and I have rebuilt with `cargo clean`.

**Comment by antimora** [comment]
In that case, I recommend updating your OS. It could be there is a problem with the linked OS libraries. If you're okay removing ~/.cache, then you should remove it and try it again. Some people report it helps. You can also reinstall cargo.

**Comment by temrix** [comment]
I tried reinstalling cargo and updating to the next release both of which did not work regarding to this problem. It seems I need to reinstall.
