### ISSUE TITLE
README references burn-no-std-tests which sends you to a 404 page.

### ISSUE THREAD

**Issue by Poxxy** [burn-rs/burn#483]
In the README there is a section about support for `no_std` which has a link to a supposed example of `burn-no-std-tests`. The link is here: https://github.com/burn-rs/burn/tree/main/examples/burn-no-std-tests

This link sends you to a 404 page as there is no such example in that directory.

**Comment by antimora** [comment]
Thanks. Submitted a PR to fix the broken link: https://github.com/burn-rs/burn/pull/484
