### ISSUE TITLE
 Simplify tensor casting between different kinds

### ISSUE THREAD

**Issue by antimora** [burn-rs/burn#487]
**Feature Description**
We propose that we simplify the process of casting tensors between different kinds. Currently, converting a tensor of integer kind to a tensor of float kind is not intuitive and feels clunky. 

**Current Behavior**
Here's an example of what needs to be done currently to perform this casting:

```rust
use burn_ndarray::NdArrayBackend;
use burn::tensor::{Tensor, Data, Int};

type B = NdArrayBackend<f32>;

// create an int tensor with [0, 1, 2, 3, 4, 5]
let tensor_int = Tensor::<B, 1, Int>::arange(0..6);

// convert int tensor to float tensor
let tensor_float:Tensor::<B, 1> = Tensor::from_data(
    tensor_int
        .into_data()
        .convert()
);

println!("{}", tensor_float);
```

**Desired Behavior**
Ideally, there should be a simpler, more intuitive way to perform this kind of casting. This would improve the usability of the library and potentially reduce errors or confusion. Perhaps, the following API example could be used:

```rust
use burn_ndarray::NdArrayBackend;
use burn::tensor::{Tensor, Data, Int};

type B = NdArrayBackend<f32>;

// create an int tensor with [0, 1, 2, 3, 4, 5]
let tensor_int = Tensor::<B, 1, Int>::arange(0..6);

// convert int tensor to float tensor
let tensor_float = tensor_int.to_float();

println!("{}", tensor_float);
```

**Comment by nathanielsimard** [comment]
I'm not sure about `to_float` since it can be ambiguous with `from_floats`, `from_bools` and `from_ints` that create tensors from data. An idea API would look like this for me.

```rust
use burn_ndarray::NdArrayBackend;
use burn::tensor::{Tensor, Data, Int};

type B = NdArrayBackend<f32>;

// create an int tensor with [0, 1, 2, 3, 4, 5]
let tensor_int = Tensor::<B, 1, Int>::arange(0..6);

// convert int tensor to float tensor
let tensor_float = tensor_int.cast::<Float>();

println!("{}", tensor_float);
``` 

I think this is doable without having to import any trait using associative types. (Already present in the `TensorKind` trait).
@antimora what are your thoughts?

**Comment by antimora** [comment]
> I'm not sure about `to_float` since it can be ambiguous with `from_floats`, `from_bools` and `from_ints` that create tensors from data. An idea API would look like this for me.
> 
> ```rust
> use burn_ndarray::NdArrayBackend;
> use burn::tensor::{Tensor, Data, Int};
> 
> type B = NdArrayBackend<f32>;
> 
> // create an int tensor with [0, 1, 2, 3, 4, 5]
> let tensor_int = Tensor::<B, 1, Int>::arange(0..6);
> 
> // convert int tensor to float tensor
> let tensor_float = tensor_int.cast::<Float>();
> 
> println!("{}", tensor_float);
> ```
> 
> I think this is doable without having to import any trait using associative types. (Already present in the `TensorKind` trait). @antimora what are your thoughts?

`cast` probably is better for converting specific datatype like it's done in [tensorflow's cast API like this](https://www.tensorflow.org/api_docs/python/tf/cast):

```python
import tensorflow as tf

# Create an integer tensor.
tensor_int = tf.constant([1, 2, 3], dtype=tf.int32)

# Cast it to float.
tensor_float = tf.cast(tensor_int, tf.float32)

```
But since we just converting from float to int, and vice versa, it's better we have dedicated methods. We can take PyTorch's approach. We can get rid off `to_` prefix. So it will sound like tensor float for `tensor.float()` conversion.

```python
import torch

# Create an integer tensor.
tensor_int = torch.tensor([1, 2, 3], dtype=torch.int32)

# Cast it to float.
tensor_float = tensor_int.float()

# And back to int
tensor_int_again = tensor_float.int()
```

**Comment by trfdeer** [comment]
> ```python
> import torch
> 
> # Create an integer tensor.
> tensor_int = torch.tensor([1, 2, 3], dtype=torch.int32)
> 
> # Cast it to float.
> tensor_float = tensor_int.float()
> 
> # And back to int
> tensor_int_again = tensor_float.int()
> ```

This approach is to be followed for implementing this?

**Comment by antimora** [comment]
@trfdeer, yes, that's the design we have settled on. @nathanielsimard has okayed on this API.

**Comment by trfdeer** [comment]
I've created a PR for this. Let me know if you have any suggestions for improving the PR or if you'd like me to modify the implementation.
