### ISSUE TITLE
Conv1dConfig stride always 1

### ISSUE THREAD

**Issue by Gadersd** [burn-rs/burn#505]
The burn 0.7.0 version on crates.io has the issue that the stride for Conv1dCondif is always 1. I noticed that this is fixed in the GitHub code. When will the next version be released on crates.io? One of my projects requires a stride other than 1.

**Comment by antimora** [comment]
I think it would be a while for the 0.8 release since we are working one a bigger components currently but we could release a patch version 0.7.1 to fix this and other minor bugs discovered. What do you, @nathanielsimard ?

**Comment by antimora** [comment]
Linking the fix PR: https://github.com/burn-rs/burn/pull/451

**Comment by nathanielsimard** [comment]
@antimora I think we will release the 0.8 version next week, max in two weeks, so we'll skip the 0.7.1 version and encourage people to use `branch = "main"` for a few days.
