### ISSUE TITLE
Show and Tell: Whisper Implementation

### ISSUE THREAD

**Issue by Gadersd** [burn-rs/burn#519]
I ported OpenAI's Whisper transcription model to burn. The project page is https://github.com/Gadersd/whisper-burn. All the model files I have converted are available at https://huggingface.co/Gadersd/whisper-burn. I welcome any feedback.

Has the repository that will hold the burn implementations of popular models been created yet? I would like to contribute and am interested in porting more models over to burn.

**Comment by antimora** [comment]
Super! Thanks for letting us know about this project. Yes, we are planning to create a separate repo to hold all popular modules. 

So you know, actually I am interested in speech recognition and working on my speech related project. So your implementation is personally exciting.

Tagging @nathanielsimard and @louisfd so they're aware.

**Comment by antimora** [comment]
You should announce it on Discord. I think people will be excited to know and learn.

**Comment by antimora** [comment]
@nathanielsimard and I were discussing about creating a new repository burn-model-zoo that will host popular models. We could include your code or point to your repository.

**Comment by Gadersd** [comment]
You are welcome to include my code or point to the repo as long as credit is given.

**Comment by antimora** [comment]
We have created [burn-rs/models repository](https://github.com/burn-rs/models) and added the links. Also updated [the main readme section](https://github.com/burn-rs/burn#pre-trained-models) to point to models repository. 

Closing this ticket as done per action item.
