### ISSUE TITLE
Show and Tell: Llama2 Burn Port

### ISSUE THREAD

**Issue by Gadersd** [burn-rs/burn#555]
I eagerly ported Llama2 to burn after I got whisper working. You can check out the project at https://github.com/Gadersd/llama2-burn. I've tested it so far on llama-7b-chat and after some initial gibberish which was entirely the model's own fault I got some coherent output. Any feedback would be great as I'm always seeking to improve! If this isn't the proper place to announce this let me know.

**Comment by ianpurton** [comment]
This should probably be linked to in the examples section on the front page.

Llama2 on burn is a great example of the possibilities of Burn.

**Comment by antimora** [comment]
> This should probably be linked to in the examples section on the front page.
> 
> Llama2 on burn is a great example of the possibilities of Burn.

Thanks. We are still figuring out where to place the links, that'd be one of the action items from this ticket.

**Comment by antimora** [comment]
We have created [burn-rs/models repository](https://github.com/burn-rs/models) and added the links. Also updated [the main readme section](https://github.com/burn-rs/burn#pre-trained-models) to point to models repository. 

Closing this ticket as done per action item.
