### ISSUE TITLE
No CPU Device on Mac M2

### ISSUE THREAD

**Issue by Gadersd** [burn-rs/burn#565]
Someone experienced a `No CPU device found` error on a Mac M2 using the burn_wgpu backend when trying to run the convert binary on https://github.com/Gadersd/llama2-burn.

**Comment by nathanielsimard** [comment]
The `WgpuDevice::Cpu` isn't guarantee to be available with all graphics APIs. I think it's only available when the driver has a software rendering mode. If you want to run llama2 on a Mac, you can use `WgpuDevice::default()` using Metal, or the `tch` backend.

**Comment by antimora** [comment]
If this person wants to run CPU for sure, then you can use burn-ndarray backend. For the latest Mac that has [MacOS Accelerate library](https://developer.apple.com/documentation/accelerate?language=objc), you can enable `accelerate` feature flag to speed up computation.
