### ISSUE TITLE
How do I subtract a scalar from all values in a slice of a tensor.

### ISSUE THREAD

**Issue by xgillard** [burn-rs/burn#580]
I am currently trying to port CSRNet to Burn. So far, it has been a very pleasant experience and I want to thank you all for that (I had to make some light fixes in the implementation of the burn-import code related to maxpool2d to get it working, but I will make a PR for that later once I have a working csrnet). 

The question I have now, is I need to translate the following:
```python
img[0,:,:]=img[0,:,:]-92.8207477031
img[1,:,:]=img[1,:,:]-95.2757037428
img[2,:,:]=img[2,:,:]-104.877445883
```

And I am not sure of how to do it... I came out with the following but I am not too sure if that is okay:
```rust
let mut img = Tensor::from_floats(Data::from(im.into_vec().as_slice()))
        .reshape(Shape::from([3, W, H]));

let d0 = img.clone().select(0, Tensor::from_ints([0, iw, 0, ih])).add_scalar(-92.8207477031);
let d1 = img.clone().select(1, Tensor::from_ints([0, iw, 0, ih])).add_scalar(-95.2757037428);
let d2 = img.clone().select(2, Tensor::from_ints([0, iw, 0, ih])).add_scalar(-104.877445883);

img = img.select_assign(0, Tensor::from_ints([0, iw, 0, ih]), d0);
img = img.select_assign(1, Tensor::from_ints([0, iw, 0, ih]), d1);
img = img.select_assign(2, Tensor::from_ints([0, iw, 0, ih]), d2);
```
Would anyone mind tell me if that's ok ? And, if there is any fix to make in the doc, I think the examples for `Tensor::select` and `Tensor::select_assign` might be a little clearer.

Thank you beforehand for the help !

**Comment by nathanielsimard** [comment]
I think you should use `slice` instead of `select`.

```rust
let img = img.clone().slice_assign([0..1], img.slice([0..1]) - 92.8207477031);
let img = img.clone().slice_assign([1..2], img.slice([1..2]) - 95.2757037428);
let img = img.clone().slice_assign([2..3], img.slice([2..3]) - 104.877445883);
```

**Comment by xgillard** [comment]
Thank you so much for your quick reply
