### ISSUE TITLE
Show and Tell: Stable Diffusion in Burn

### ISSUE THREAD

**Issue by Gadersd** [burn-rs/burn#592]
This was a tough one. After dealing with the fairly elegant architectures of Whisper and Llama 2 I expected something similar here but nope. Stable Diffusion feels like a jungle gym of a model with modules within modules and data flowing in complex ways, but some time after I started seeing floating point numbers with my eyes closed I finally got it working. Check it out at [Stable-Diffusion-Burn](https://github.com/Gadersd/stable-diffusion-burn) and make your fantasies a reality. If you want to see more like this such as Stable Diffusion XL in burn consider supporting me via my [Patreon](https://patreon.com/Gadersd?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=creatorshare_creator&utm_content=join_link).

**Comment by antimora** [comment]
We have created [burn-rs/models repository](https://github.com/burn-rs/models) and added the links. Also updated [the main readme section](https://github.com/burn-rs/burn#pre-trained-models) to point to models repository. 

Closing this ticket as done per action item.

**Comment by antimora** [comment]
(keeping it pinned for a few days)
