### ISSUE TITLE
Autotune WGPU: empty context cache

### ISSUE THREAD

**Issue by louisfd** [burn-rs/burn#619]
Currently, the context keeps in a cache every kernel it has used. 
With autotune, this context cache (not the tuner cache!) then becomes polluted with all the kernels that have been tried but have not been chosen. We should keep only the winning kernel. 
It might be simpler to empty the cache at the end of the tuning than to not add to the cache.

**Comment by agelas** [comment]
@louisfd @nathanielsimard Long time no see, it's been a while but I can take this one.

**Comment by agelas** [comment]
@louisfd Is there a way to reliably regenerate a `TemplateKey ` from an `AutoTuneKey`? The most straightforward way to do this in my mind is to take advantage of some interior mutability and pass in a reference to the `Tuner`'s context to `tune()`, and clear the context cache of everything but the value of the winning kernel id.

**Comment by louisfd** [comment]
Hi @agelas, 
I think it would be non-trivial, as `TemplateKey` and `AutotuneKey` were designed as very different concepts. 

`TemplateKey` maps for instance the string `Dynamic("MatmulTiling2DContiguous { b_m: 128, b_n: 128, b_k: 32, t_m: 16, t_n: 16, workgroup_size_x: 8, workgroup_size_y: 8, _elem: PhantomData<f32> }")` to the actual kernel having these parameters, whose type is `Arc<ComputePipeline>`, while `AutotuneKey` maps the string `AutoTuneKey { shapes: [[2, 2], [2, 2]], ops: "matmul f32", device: "\"Apple M2 Pro\"", graphics_api: "Metal" }` to a `Box<dyn Any + Send + Sync>` which is an abstraction to allow any function. 

But this function is not necessarily made from a template, as we wanted our tuner to be very general. So I do not think there is a straightforward way to do exactly what you want.
