### ISSUE TITLE
Add Dilation Option to MaxPool1d and MaxPool2d Functions

### ISSUE THREAD

**Issue by antimora** [burn-rs/burn#622]
#### Description

The MaxPool1d and MaxPool2d functions currently lack the support for dilation options, a feature [supported by PyTorch](https://pytorch.org/docs/stable/generated/torch.nn.MaxPool2d.html) and required by ONNX MaxPool ([ONNX MaxPool Documentation](https://onnx.ai/onnx/operators/onnx__MaxPool.html)). This feature would align our implementation with industry standards and provide additional functionality for our users.

#### Use case

Dilation options in MaxPool1d and MaxPool2d functions allow users to control the spacing between the values in the output matrix. This feature is critical for certain applications in deep learning and computer vision, including object detection, image segmentation, and feature extraction.

#### Proposed Solution

- Add an optional `dilation` parameter to the MaxPool1d and MaxPool2d functions.
- Implement necessary computations to support dilation as described in the PyTorch and ONNX MaxPool specifications.
- Update the corresponding unit tests and documentation to cover this new feature.

### Additional context

PyTorch supports dilation in its MaxPool1d and MaxPool2d functions, and ONNX MaxPool requires it too, as described in the [official documentation](https://onnx.ai/onnx/operators/onnx__MaxPool.html). Including this feature would ensure compatibility with these frameworks and allow users to replicate models and workflows that leverage dilation in MaxPool1d and MaxPool2d operations.

### Action Items
1. [ ] Update MaxPool1d
2. [ ] Update MaxPool2d
3. [ ] Update burn-import

**Comment by antimora** [comment]
@CaioPiccirillo would you like to take this up, since you're fresh working with MaxPool? I have discovered this is needed for ONNX Op to be fully compatible.

**Comment by CaioPiccirillo** [comment]
Yeah, sure! 😀

**Comment by antimora** [comment]
> Yeah, sure! 😀

Thank you!

**Comment by antimora** [comment]
Closed as complete per #668. Thank you, @caiopiccirillo
