### ISSUE TITLE
How to "broadcast" model input?

### ISSUE THREAD

**Issue by wbrickner** [burn-rs/burn#631]
I want to take a model that accepts `Tensor<B, 1, Float>` and run my forward pass over an entire 2D batch of independent inputs of shape `[batch, feature_dim]` and receive back a 2D tensor of shape `[batch, output_dim]`.

I can't find a way to do this, it complains that my model only accepts `Tensor<B, 2, Float>`.

Should I just redefine all my models to be `Tensor<B, 2, Float>`?

**Comment by nathanielsimard** [comment]
You can look at how the forward pass on the Linear module is done. You need to declare the dimension as a const generic and unsqueeze the input tensor. Let me know if you need more help.
