### ISSUE TITLE
Panic: index out of bounds when using flatten for going from a 3D -> 1D array

### ISSUE THREAD

**Issue by mrvollger** [burn-rs/burn#646]
**Describe the bug**
When I try to flatten a 3D tensor I get a panic message:
```
panicked at 'index out of bounds: the len is 1 but the index is 1', /Users/mrvollger/Desktop/repos/burn/burn-tensor/src/tensor/api/base.rs:147:9
```
This might not be a bug, but I think should be a Error message instead of a panic if it is not a bug. 

**To Reproduce**
Here is a test case that reproduces it:
```rust
#[cfg(test)]
mod test {
    use burn::tensor::{Shape, Tensor};
    use burn_ndarray::NdArrayBackend;
    type Backend = NdArrayBackend<f32>;

    #[test]
    fn error_example() {
        let tensor = Tensor::<Backend, 3>::ones(Shape::new([1, 5, 15]));
        let flattened_tensor: Tensor<Backend, 1> = tensor.flatten(1, 2);
        let expected_shape = Shape::new([75]);
        assert_eq!(flattened_tensor.shape(), expected_shape);
    }
}
```

**Expected behavior**
I think the expected behavior is for the shape of the output to be `Shape::new([75]);`. Maybe that logic is not correct, but even so avoiding a panic here and having an error would be really helpful!

I ran into this trying to load an `onnx` model created using `pytorch`, so I think all the logic is correct in the model since I have used it extensively in pytorch. 

**Screenshot**
This is a screen shot of the onnx model I am trying to load and a link to the onnx model incase it is of interest. But you do not need it to recreate the error, the minimal test case enough is above. 
<img width="268" alt="image" src="https://github.com/burn-rs/burn/assets/6935283/7a663e18-ddae-4694-afca-c7a81e67cd28">
https://github.com/fiberseq/fibertools-rs/raw/onnx_burn/src/model/revio.onnx

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: main (latest)

This might be a very silly mistake on my part... but I'd appreciate any help!

Thanks,
Mitchell

**Comment by mrvollger** [comment]
Maybe this is special case when the non flattened and leading dimension(s) are "1" and are maybe pytorch and onnx expects `Shape::new([1, 75]);` to be allowed to be "cast" into `Shape::new([75]);`?

**Comment by nathanielsimard** [comment]
This function should not compile. However, since constant expression evaluation isn't fully stable yet, we cannot automatically determine the rank of the tensor. In this specific case, we flatten dimensions 1 and 2, which results in a tensor of rank 2. Despite this, we essentially 'force' it to behave as if it were rank 1. We should probably add a check to print better error messages.

**Comment by antimora** [comment]
I will look into this since I have worked on `flatten` method.

**Comment by mrvollger** [comment]
Awesome. Thanks to both of you! 

Let me know if there is anything I can share that would be of use!

**Comment by mrvollger** [comment]
Thanks @antimora! I really appreciate the fix. I will test the PR against my expectations for the model :)
