### ISSUE TITLE
How to efficiently write timeseries "window" models?

### ISSUE THREAD

**Issue by wbrickner** [burn-rs/burn#674]
Apologies if this is a stupid question.

I'm wondering if there's an elegant and efficient way to write timeseries models that look backwards N timesteps, without duplicating the underlying timeseries into many separate windows.

Let's say I have a vector timeseries stored in a tensor, shaped like `[ timestep_count, feature_count ]`.
I want my model to operate on an input `[n, feature_count]`. In forward pass, all of these predictions should occur in parallel as a single operation. 

```text
 ──[timesteps, features]──────────────────────── 
┌─┬─┬─┬─┬─┬─┬─┬─┬─┬─┬─┬─┬─┬─┬─┬─┬─┬─┬─┬─┬─┬─┬─┬─┐
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │
├─┴─┴─┴─┴─┴─┴─┴─┼─┴─┴─┴─┴─┴─┴─┴─┴─┴─┴─┴─┴─┴─┴─┴─┘
│   window 0    │                                
└─┬─────────────┴─┐                              
  │   window 1    │                              
  └─┬─────────────┴─┐                            
    │   window 2    │                            
    └─┬─────────────┴─┐                          
      │   window 3    │                          
      └───────────────┘                          
```

I could prepare a tensor that is `[window_count, lookback_size, feature_count]`, with lots of duplication. This is bad for GPU memory limits and bandwidth / locality, and very messy: `timestep_count` is very high, this is a bad solution and very ugly.

Is there a way to write this in burn that is simple and elegant and efficient? **Like, perhaps to create a tensor of shape `[window_count, lookback_size, feature_count]` which aliases itself?**

Thank you.

**Comment by wbrickner** [comment]
After some more research, it's my understanding that pytorch has an API for exactly this case, the `unfold` function. However, `burn` does not expose this API as part of `Tensor`.

Can we get that implemented?

**Comment by nathanielsimard** [comment]
Burn doesn't currently support `fold` and `unfold` but it's something we are looking to support. Conv1d is often used with timeseries data, it's efficient and you can calculate the receptive field to know how much "window" is considered https://medium.com/@santi.pdp/receptive-fields-in-convolutional-neural-networks-6368a699d838

**Comment by wbrickner** [comment]
Is there a way to step outside the burn abstraction and apply unsupported pytorch operations? The operations are done at startup without any autodiff or anything, it's just for training data.

**Comment by nathanielsimard** [comment]
@wbrickner Yes, though it's not yet documented, I'm going to make a section on this on the guide.

```rust
/// Define a new backend trait with additional methods
trait MyAugmentedBackend: burn::tensor::Backend {
    fn my_new_function_to_support<const: D: usize>(input: Tensor<Self, D>) -> Tensor<Self, D>;
}

/// Implement the augmented backend for an existing backend.
impl<E: TchElement> MyAugmentedBackend for TchBackend<E> {
    fn my_new_function_to_support<const: D: usize>(input: Tensor<Self, D>) -> Tensor<Self, D> {
        let input_tch: TchTensor<E> = input.into_primitive();
        input_tch.tensor.any_tch_function();
        ...
    }
}

/// Instead of B: Backend, use B: MyAugmentedBackend to use the additional method.
impl<B: MyAugmentedBackend> MyModule<B> {
    fn forward(tensor: Tensor<B, 3>) -> Tensor<B, 3> {
        let x = B::my_new_function_to_support(tensor);
        ...
    }
}
```

I didn't compile the code above, it's just pseudo code but it gives the ideas how you can augment the Backend trait with your own functions.

**Comment by wbrickner** [comment]
That's almost perfect, but I can't implement that external to burn because the `tensor` field is private. Any suggestion?

**Comment by nathanielsimard** [comment]
> That's almost perfect, but I can't implement that external to burn because the `tensor` field is private. Any suggestion?

Simple, we should make it public 😅

**Comment by wbrickner** [comment]
I'm using a function like this:

```rust
fn windows(lookback: usize, input: Tensor<TchBackend<f32>, 2>) -> Tensor<TchBackend<f32>, 3> {
  let window_count = input.shape().dims[0] - lookback + 1;
  let features = input.shape().dims[1];

  let mut prim: TchTensor<f32, 2> = input.into_primitive();
  prim.tensor = prim.tensor.unfold(0, lookback as i64, 1);

  println!("prim.size: {:?}", prim.tensor.size());

  let x = Tensor::<TchBackend<f32>, 2>::from_primitive(prim);

  x.reshape([
    window_count,
    lookback,
    features
  ])
}
```

to create windows. 

It panics:

```rust
prim.size: [440913, 17, 120]
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', /Users/wbrickner/.cargo/git/checkouts/burn-ad3e755ad2440f54/17ce603/burn-tensor/src/tensor/shape.rs:32:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:162:5
   3: <burn_tensor::tensor::shape::Shape<_> as core::convert::From<alloc::vec::Vec<i64>>>::from
             at /Users/wbrickner/.cargo/git/checkouts/burn-ad3e755ad2440f54/17ce603/burn-tensor/src/tensor/shape.rs:32:13
   4: burn_tch::tensor::TchTensor<E,_>::shape
             at /Users/wbrickner/.cargo/git/checkouts/burn-ad3e755ad2440f54/17ce603/burn-tch/src/tensor.rs:65:9
   5: burn_tch::ops::tensor::<impl burn_tensor::tensor::ops::tensor::TensorOps<burn_tch::backend::TchBackend<E>> for burn_tch::backend::TchBackend<E>>::shape
             at /Users/wbrickner/.cargo/git/checkouts/burn-ad3e755ad2440f54/17ce603/burn-tch/src/ops/tensor.rs:79:9
   6: <burn_tensor::tensor::api::kind::Float as burn_tensor::tensor::api::base::BasicOps<B>>::shape
             at /Users/wbrickner/.cargo/git/checkouts/burn-ad3e755ad2440f54/17ce603/burn-tensor/src/tensor/api/base.rs:749:9
   7: burn_tensor::tensor::api::base::Tensor<B,_,K>::shape
             at /Users/wbrickner/.cargo/git/checkouts/burn-ad3e755ad2440f54/17ce603/burn-tensor/src/tensor/api/base.rs:55:9
   8: <[usize; D2] as burn_tensor::tensor::api::base::ReshapeArgs<_>>::into_shape
             at /Users/wbrickner/.cargo/git/checkouts/burn-ad3e755ad2440f54/17ce603/burn-tensor/src/tensor/api/base.rs:990:57
   9: burn_tensor::tensor::api::base::Tensor<B,_,K>::reshape
             at /Users/wbrickner/.cargo/git/checkouts/burn-ad3e755ad2440f54/17ce603/burn-tensor/src/tensor/api/base.rs:92:21
```

The panic origin:

```rust
impl<const D: usize> From<Vec<i64>> for Shape<D> {
    fn from(shape: Vec<i64>) -> Self {
        let mut dims = [1; D];
        for (i, dim) in shape.into_iter().enumerate() {
            dims[i] = dim as usize;
        }
        Self::new(dims)
    }
}
```

descends from the check macro:

```rust
impl<const D2: usize> ReshapeArgs<D2> for [usize; D2] {
    fn into_shape<B: Backend, const D: usize, K: BasicOps<B>>(
        self,
        tensor: &Tensor<B, D, K>,
    ) -> Shape<D2> {
        let shape = Shape::from(self);

        check!(TensorCheck::reshape_args_usize(&shape, &tensor.shape()));

        shape
    }
}
```

because the `D` const generic of my `x` tensor is still `2`, rather than `3`, causing it to create an incorrectly sized buffer in the function that ultimately panics.

Any idea how to get around this? The whole issue is I do an FFI call that changes the dimension of the tensor but the rust type system doesn't know, and there's no way I can see to strongarm the const generic to be 3.

**Comment by wbrickner** [comment]
Okay turns out there is a simple way to lie to the type system.

**Partial Solution:**

```rust
fn windows(lookback: usize, input: Tensor<TchBackend<f32>, 2>) -> Tensor<TchBackend<f32>, 3> {
  let device = input.device();

  let prim: TchTensor<f32, 2> = input.into_primitive();
  let prim_tensor = prim.tensor.unfold(0, lookback as i64, 1);

  Tensor::from_primitive(
    TchTensor::<f32, 3>::new(
      prim_tensor
    )
  ).to_device(&device)
}
```

**However:**
- input tensor is `[441032, 17]`,
- resulting tensor is of shape `[440913, 17, 120]`, 
- when I desire it to be of shape `[440913, 120, 17]`

What have I done wrong?

**Comment by wbrickner** [comment]
**Final Solution:**

```rust
fn windows(lookback: usize, input: Tensor<TchBackend<f32>, 2>) -> Tensor<TchBackend<f32>, 3> {
  let device = input.device();
  // println!("input shape: {:?}", input.shape());
  let [timesteps, features] = input.shape().dims;

  Tensor::from_primitive(
      TchTensor::<f32, 3>::new(
        input
          .into_primitive()
          .tensor
          .unfold(0, lookback as i64, 1)
      )
    )
    .to_device(&device)
    .reshape([
      timesteps - lookback + 1,
      lookback,
      features
    ])
}
```

Is this correct?

**Comment by nathanielsimard** [comment]
Well, when going lower level with the tch backend, you have less checks and it's the job of the coder to declare the correct rank of the output tensor. The function you provided seems fine, but I'm not sure if I would do a reshape VS just swapping the dimenssion 1 and 2. It depends on what you want.

Also, I'm not sure if you need to call `to_device`. The device of the tensor should not change after the unfold call.

**Comment by antimora** [comment]
If this is resolved, can we close it? Or should we can keep it open if we have some action items left?

**Comment by nathanielsimard** [comment]
I created issues for supporting the fold and unfold operations without using a backend extension: #786 #787
