### ISSUE TITLE
serde_rusqlite is LGPL

### ISSUE THREAD

**Issue by dae** [burn-rs/burn#719]
While looking through burn's dependencies, I noticed that serde_rusqlite is LGPL. Just thought I'd bring it to your attention if you're not already aware, as the LGPL is [somewhat problematic](https://github.com/rpm-software-management/librpm.rs/issues/21) in Rust, and it's a bit surprising to have (L)GPL dependencies in an MIT/Apache-licensed project.

**Comment by dae** [comment]
Sorry, I've just seen that you guys are [already aware](https://github.com/twistedfall/serde_rusqlite/issues/21).

**Comment by dae** [comment]
You're no doubt already aware of this, but just stating it for the benefit of other onlookers: while static linking is not an issue for Burn itself, it can be a problem for apps that include Burn in them. As I understand it, the LGPL requires that a distributed program allow replacing any included LGPL code with a modified version. In other languages where the LGPL code is in a dynamic library, users can just drop in a replacement dll, but with Rust and static linking, that typically means you need to provide your entire program's source code so that the user can recompile it. It may be possible to compile the other parts of the app into one or more rlibs and distribute those so that the user can do the final build step, but I'm not sure how practical that would actually be, and I suspect any apps that can't distribute their source code would just avoid LGPL dependencies instead.

**Comment by antimora** [comment]
Hopefully, the author can re-release under MIT/Apache2. I'll copy your response as our reasoning.

**Comment by antimora** [comment]
Since I worked on this part, I wanted to share one viable option. The worst case scenario, we can write own small part needed for our dataset use case. We only use serde_rustqlite to deserialize a table row into a user provided struct. Previously, deserialization was happening from a JSON file. The logic isn't too complicated, so it can be done. In fact, I was going to do it but I have discovered someone already had done it. I hope it does not come to this (just sharing this as an option) - I want to be spending on other cool burn parts =)

**Comment by dae** [comment]
Hopefully it doesn't come to that!

**Comment by antimora** [comment]
This issue has popped up again and we need to fix it soon. Here’s what we plan to do next:

	1.	Separate the Hugging Face dataset that uses SQLite serde, using a feature flag. Note: We need SQLite serde for this, not the SQLite dataset in Burn. This will improve the program and allow users to use SQLite dataset without needing the Hugging Face dataset.
	2.	Submit a pull request to change the license. We hope the current and past authors will agree to this change.
	3.	If the PR is rejected, we’ll create our own SQLite row deserializer. This should be relatively easy since we only need a few features from SQLite serde.

**Comment by antimora** [comment]
I have submitted a PR (https://github.com/twistedfall/serde_rusqlite/pull/24) to re-license under MIT/Apache-2. The author and one of the contributors have agreed to the change. Waiting for one remaining (fingers crossed).

**Comment by antimora** [comment]
My [license change PR](https://github.com/twistedfall/serde_rusqlite/pull/24) was accepted and released. I'll update Burn's version to use the updated version.
