### ISSUE TITLE
log4rs does not appear to be actively maintained

### ISSUE THREAD

**Issue by dae** [burn-rs/burn#732]
It currently depends on a old time crate that results in security warnings in GitHub and in invocations of commands like cargo-deny. A fix was submitted to them in https://github.com/estk/log4rs/pull/241, but has not been merged 6 months later. The tracing crate appears to be what's popular these days; would there be interest in a PR that switched out log4rs for something like the tracing crate if it proves practical to do so?

**Comment by nathanielsimard** [comment]
I don't mind changing the logging crate; the only requirements are:

* Can log to a file (cross-platform)
* Can filter logs (wgpu is very verbose)

That's it! Everything is pretty contained in this file: https://github.com/burn-rs/burn/blob/main/burn-train/src/learner/log.rs

**Comment by bconn98** [comment]
Darn, just to late. log4rs is coming back!

**Comment by antimora** [comment]
@bconn98 what do you mean?

**Comment by nathanielsimard** [comment]
We switched to https://github.com/tokio-rs/tracing

**Comment by bconn98** [comment]
Yup, saw you guys switched. Was just noting that log4rs is coming back from inactivity. I’m working with the previous maintainer to keep it going.
