### ISSUE TITLE
Failed tests, and initial checks

### ISSUE THREAD

**Issue by dae** [burn-rs/burn#741]
On my first PR, the test execution of ./run-check.sh took around 15 minutes to run, and was rather daunting - I found myself thinking "will this ever end?". Subsequent runs are much faster. If the initial run is expected to be slow, it might be worth mentioning something in the PR template to re-assure users that it's not going to take forever.

Another issue is that when I run ./run-check.sh, I consistently get the following errors. I presume it's because of my system (Debian OldStable/RX 6600). Any ideas on how I could avoid these errors? I missed some docstring errors in a recent PR, and am not sure if that's because run-check was terminating early, or because the docstring tests are not covered by that script.

```
---- tests::aggregation::tests::test_should_mean stdout ----
thread 'tests::aggregation::tests::test_should_mean' panicked at 'assertion failed: `(left == right)`
  left: `Data { value: [2.4999998], shape: Shape { dims: [1] } }`,
 right: `Data { value: [2.5], shape: Shape { dims: [1] } }`', burn-wgpu/src/lib.rs:49:5

---- tests::aggregation::tests::test_should_mean_last_dim stdout ----
thread 'tests::aggregation::tests::test_should_mean_last_dim' panicked at 'assertion failed: `(left == right)`
  left: `Data { value: [0.99999994, 3.9999998], shape: Shape { dims: [2, 1] } }`,
 right: `Data { value: [1.0, 4.0], shape: Shape { dims: [2, 1] } }`', burn-wgpu/src/lib.rs:49:5

---- tests::div::tests::should_support_div_ops stdout ----
thread 'tests::div::tests::should_support_div_ops' panicked at 'assertion failed: `(left == right)`
  left: `Data { value: [0.0, 1.0, 1.0, 1.0, 1.0, 1.0], shape: Shape { dims: [2, 3] } }`,
 right: `Data { value: [0.0, 1.0, 1.0, 0.99999994, 1.0, 1.0], shape: Shape { dims: [2, 3] } }`', burn-wgpu/src/lib.rs:49:5


failures:
    tests::aggregation::tests::test_should_mean
    tests::aggregation::tests::test_should_mean_last_dim
    tests::div::tests::should_support_div_ops
```

**Comment by nathanielsimard** [comment]
Most tests are using `assert_approx_eq`, but the ones you listed are old and use `assert_eq!`, which hasn't been a problem on my computer or the CI. However, it can produce flaky tests on some systems, so we should update them!

I agree that we should document the `run-check.sh` execution time. When nothing is compiled or even downloaded, the first run can be slow, but the following ones should be faster. Note that `run-check.sh` is comprehensive; it runs on multiple targets with a ton of feature flags. A simple `cargo test` is better when working.
