### ISSUE TITLE
Backend Attention Function

### ISSUE THREAD

**Issue by Gadersd** [burn-rs/burn#742]
### Feature description

Add a multihead qkv attention function to burn and efficiently implement it for each backend.

### Feature motivation

Torch 2.0 uses flash attention by default which is much faster and uses less memory than high level implementations such as the one currently used in burn. Having burn call flash attention from tch would significantly improve performance on transformer-based models.

**Comment by nathanielsimard** [comment]
I don't think we should add an attention function in the backend API for now, though we need a way to let backends optimize the computation graphs and do operation fusion.

For now I think the best approach is to do a backend extension for flash attention: https://github.com/burn-rs/burn/blob/main/burn-book/src/advanced/backend-extension/README.md

We just merged the guide and I think it would be very useful for your project :)

Let me know if you need help or if you have any comment on the new guide advanced section!

**Comment by Gadersd** [comment]
I tried following the example from the book but I get about 30 errors like:
```
error[E0277]: the trait bound `<B as ADBackend>::InnerBackend: backend::Backend` is not satisfied
   --> src/model/stablediffusion/mod.rs:191:10
    |
191 | #[derive(Module, Debug)]
    |          ^^^^^^ the trait `backend::Backend` is not implemented for `<B as ADBackend>::InnerBackend`
    |
note: required by a bound in `stablediffusion::LatentDecoder`
   --> src/model/stablediffusion/mod.rs:192:29
    |
192 | pub struct LatentDecoder<B: Backend> {
    |                             ^^^^^^^ required by this bound in `LatentDecoder`
    = note: this error originates in the derive macro `Module` (in Nightly builds, run with -Z macro-backtrace for more info)
```

The backend code is:
```
pub trait Backend: burn::tensor::backend::Backend {
    fn qkv_attention(q: Self::TensorPrimitive<3>,
        k: Self::TensorPrimitive<3>,
        v: Self::TensorPrimitive<3>,
        mask: Option<Self::TensorPrimitive<2>>,
        n_head: usize,) -> Self::TensorPrimitive<3> {
            qkv_attention(Tensor::<Self, 3>::from_primitive(q), Tensor::from_primitive(k), Tensor::from_primitive(v), mask.map(|m| Tensor::from_primitive(m)), n_head).into_primitive()
        }

    fn attn_decoder_mask(seq_length: usize, device: &Self::Device) -> Self::TensorPrimitive<2> {
        attn_decoder_mask::<Self>(seq_length, device).into_primitive()
    }
}

use burn_autodiff;

impl<B: Backend> Backend for burn_autodiff::ADBackendDecorator<B> {}
```

**Comment by nathanielsimard** [comment]
@Gadersd If you can provide me with a link to the branch you are working on, I could go and have a look. I think you may be missing the `ADBackend` trait like with the example, but I may be wrong. Nevertheless, I think the error messages don't help much, so I could improve the guide to document such problems.

**Comment by Gadersd** [comment]
I just uploaded the flash_attention branch at https://github.com/Gadersd/stable-diffusion-xl-burn/tree/flash_attention. I'm not familiar with how burn's AD traits work so any help would be appreciated.

**Comment by nathanielsimard** [comment]
@Gadersd I found the problem, and indeed it wasn't properly described in the guide 😅. I'll have to add a new section with a new example. In short, when you create a module, you have to use the plain backend trait, not your new custom backend trait, since the `InnerBackend` can't be constrained to also implement your new custom backend:

```rust
struct Model<B: CustomBackend> { // Won't compile
    ....
}
struct Model<B: Backend> { // Will compile
}
```

In your case, you also implement `Record` and `Module` for Unet, since burn doesn't yet support `enum` module. So you have to constrain your implementation to `burn::tensor::backend::Backend` and not `MyBackend`.

In the end, I think naming the custom backend `Backend` is probably misleading, since it assumes you can use that import instead, which isn't true. I'll update the guide with a new section on creating modules.

Finally, you have to use your new Backend trait only in implementation blocks:

```rust
struct Model<B: Backend> {
    weights: Tensor<B, 2>
}

impl<B: CustomBackend> Model<B> {
   pub fn forward(&self) -> Tensor<B, 2> {
       // can call new functions only available for the custom backend.
   }
}
```

**Comment by nathanielsimard** [comment]
@Gadersd I think I can still make a fix in `burn-derive` so that you don't have to worry about which backend to use where.

**Comment by Gadersd** [comment]
I implemented your suggestions and the issues are resolved. Thanks!
