### ISSUE TITLE
Replace `run-checks.[ps1/sh]` with `cargo-xtask` pattern instead

### ISSUE THREAD

**Issue by DrChat** [burn-rs/burn#756]
Using the [`cargo-xtask`](https://github.com/matklad/cargo-xtask) pattern for implementing this script would be a better natural fit instead of the current setup.
This also gains us the benefit that this can be expanded in the future.

For developers, the invocation of these checks would be changed from:
```
> run-checks.ps1
```

to:
```
> cargo xtask run-checks
```

This should be pretty straightforward to port over, as the script is already written in Rust :)

**Comment by antimora** [comment]
Cc'ing @Luni-4

**Comment by antimora** [comment]
Closing as complete via #757
