### ISSUE TITLE
Make it easier to create tensors manually

### ISSUE THREAD

**Issue by vultix** [burn-rs/burn#76]
The easiest way I've found to create tensors so far is this:
```rust
let tensor: Tensor::<B, 2> = Tensor::from_data(Data::<f32 , 2>::from([[1.0f32, 2.0], [3.0, 4.0]]).convert());
```

This took quite a bit of digging to find out, and I'd expect this to be more straightforward.

### Suggestion 1 - Add a method directly to `Tensor`
```rust
// Note: I think it should be possible to infer the type on the LHS here (assuming the backend can be inferred from context)
let tensor: Tensor::<B, 2> = Tensor::from_array([[1.0f32, 2.0], [3.0, 4.0]]);
```

Not sure if `from_array` is the best name here.  We could also just use the `From` trait;

#### Implementation Details
This will require adding multiple impls like the following to Tensor:

```rust
impl<B: Backend>  Tensor<B, 1> {
    pub fn from_array<const D1: usize>(data: [B::Elem; D1]) -> Self {
        todo!()
    }
}

impl<B: Backend, >  Tensor<B, 2> {
    pub fn from_array<const D1: usize, const D2: usize>(data: [[B::Elem; D1]; D2]) -> Self {
        todo!()
    }
}

```

### Suggestion 2 - Add a macro
```rust
// Note: Again, the LHS type should be inferrable
let tensor: Tensor::<B, 2> = tensor![[1.0f32, 2.0], [3.0, 4.0]];
```

**Comment by vultix** [comment]
I just tried implementing suggestion 1, and got the following error from rust:
```
error[E0034]: multiple applicable items in scope
  --> examples/playground/src/main.rs:15:37
   |
15 |     let a: Tensor::<_, 1> = Tensor::from_array([1.0f32, 2.0]);
   |                                     ^^^^^^^^^^ multiple `from_array` found
   |
   = note: candidate #1 is defined in an impl for the type `Tensor<B, 1>`
   = note: candidate #2 is defined in an impl for the type `Tensor<B, 2>`
```

This is unfortunate, as I'd expect Rust to detect that only one of those `from_array` impls is applicable (both due to the array type and due to the expected tensor type)

**Comment by nathanielsimard** [comment]
Ho yeah this is a good idea, this is not supposed to be that hard, since there exist the same implementation for Data: https://github.com/burn-rs/burn/blob/main/burn-tensor/src/tensor/data.rs#:~:text=impl%3CP%3A%20std%3A%3Afmt%3A%3ADebug%20%2B%20Copy%2C%20const%20A%3A%20usize%3E%20From%3C%5BP%3B%20A%5D%3E%20for%20Data%3CP%2C%201%3E%20%7B

The only limitation is that you need one implementation for each dimension. This could look like this :

```rust

impl<B: Backend, const A: usize, const B: usize, const C: usize>
    From<[[[B::Elem; C]; B]; A]> for Tensor<B, 3>
{
    fn from(elems: [[[P; C]; B]; A]) -> Self {
       Self::from_data(Data::from(elems))
    }
}
```

**Comment by nathanielsimard** [comment]
@vultix I created a branch with a simple method that creates a tensor from floats.

It's not much, but it helps ignoring the element type (`f32` will be converted to the right one using the `convert` method from `Data`).  I'm not sure about the function name, but it is quite similar to your first proposal `from_array`. The only difference is that my function doesn't force the input to be an array, but anything that can be made into `Data<f32, D>`.

You can check it out and let me know if something could be improved :)
