### ISSUE TITLE
How to use .clamp() with a generic backend?

### ISSUE THREAD

**Issue by dae** [burn-rs/burn#795]
I fear I've probably missed something here, so a pointer in the right direction would be appreciated. As I understand it, we're supposed to define our model with just B: Backend, and only use a concrete definition in our entrypoint. We ran into trouble using .clamp() with this however - eg:

```rust
use burn::backend::WgpuBackend;
use burn::tensor::backend::Backend;
use burn::tensor::{Data, Tensor};

fn generic_code<B: Backend>() {
    let tensor = Tensor::<B, 2>::from_data(Data::<f32, 2>::from([[2., 3.], [4., 5.]]).convert());
    tensor.clamp(3., 4.);
}

fn main() {
    generic_code::<WgpuBackend>();
}
```

gives 

```
error[E0308]: arguments to this method are incorrect
   --> src/main.rs:7:12
    |
7   |     tensor.clamp(3., 4.);
    |            ^^^^^
    |
note: expected associated type, found floating-point number
```

I can work around this by changing the the function to 

```rust
fn generic_code<B: Backend<FloatElem = f32>() {
```

But that means we're no longer completely backend-agonstic. Is there a better way?

**Comment by antimora** [comment]
Does this happen for other ops or just with .clamp()? I wander if I correctly implemented this op. Here is the PR responsible for this introduction: https://github.com/burn-rs/burn/pull/550

**Comment by nathanielsimard** [comment]
Yes, you have to use element conversion trait, but the API should be generic over the element type, so I'll make a fix.

```rust
use burn::tensor::ElementConversion;

tensor.clamp(-3.elem(), -5.elem());
```

It won't be necessary after the fix.
