### ISSUE TITLE
Weird compile error on MNIST example only when copying out of repo?

### ISSUE THREAD

**Issue by CrabBucket** [burn-rs/burn#80]
**Describe the bug**

I copy pasted everything out of the MNIST src into my own project because I wanted to try making a test NN.

It does not like one of the types in data.rs yet it compiles fine in the project itself?

```error[E0308]: mismatched types
  --> TicTacToeMaster\src\data.rs:29:42
   |
29 |             .map(|tensor| tensor.reshape([1,784]))
   |                                  ------- ^^^^^^^ expected struct `Shape`, found array `[{integer}; 2]`
   |                                  |
   |                                  arguments to this function are incorrect
   |
   = note: expected struct `Shape<_>`
               found array `[{integer}; 2]`
note: associated function defined here
  --> C:\Users\itscrabs\.cargo\registry\src\github.com-1ecc6299db9ec823\burn-tensor-0.2.3\src\tensor\base.rs:31:12
   |
31 |     pub fn reshape<const D2: usize>(&self, shape: Shape<D2>) -> Tensor<B, D2> {
   |            ^^^^^^^
help: try wrapping the expression in `burn::tensor::Shape`
   |
29 |             .map(|tensor| tensor.reshape(burn::tensor::Shape { dims: [1,784] }))
   |                                          +++++++++++++++++++++++++++         +

For more information about this error, try `rustc --explain E0308`.
error: could not compile `TicTacToeMaster` due to previous error
```

**To Reproduce**

 1. Create new cargo project
 2. Copy everything in examples/mnist to the project
 3. add serde and burn to Cargo,toml
 4. cargo run
 5. See error

**Expected behavior**
Example to run

**Additional context**
I'm not so great with GitHub but just forcing it into the correct Burn shape using new() seems to fix it:
at examples/mnist/data.rs: line 29 should become:
`.map(|tensor| tensor.reshape(burn::tensor::Shape::new([1,784])))`

**Comment by nathanielsimard** [comment]
Ho my bad, this is just the new API on the `main` branch, but the version on `crates.io` is a bit outdated. Using the struct `Shape` will work on all versions. I just added a generic parameter to accept everything that implements `Into<Shape>`  (Including array) to reduce boilerplate code.
