### ISSUE TITLE
Dashboard shows wrong remaining time estimate when resuming from checkpoint

### ISSUE THREAD

**Issue by jggc** [burn-rs/burn#814]
**Describe the bug**

Resuming a training from a checkpoint will show the progress bar let's say at 25% and remaining time is not calculated based on the time per batch and number of batches remaining but rather it seems it is elapsed time and percentage of progress.

For a long training it is pretty easy to see.
**To Reproduce**

Resume from checkpoint, estimate is wrong
**Expected behavior**

When resuming my training, I expected the estimate to be calculated to the same or very close to when I stopped it. An acceptable alternative would be for the estimate to converge quickly after a few seconds / minutes towards the actual ETA.
**Screenshots**

![image](https://github.com/burn-rs/burn/assets/6208924/6e843524-4cbd-48ff-97c7-abb8b57ae374)
A single epoch takes a few hours. I resumed training about 20-30 minutes before screenshot.

**Comment by nathanielsimard** [comment]
We should compute the time remaining ignoring the previous epochs. The estimate will probably be fine in that case.
