### ISSUE TITLE
Issue when moving tensor to CUDA with torch backend

### ISSUE THREAD

**Issue by lfsalasg** [burn-rs/burn#837]
Hi guys, I am new to the Burn library. I am an user of the pytorch framework and self-taught rust developer so finding this project was amazing. I'm trying to use the torch backend with burn but I am running in the following issue (I reduced it to a basic example on what is going wrong)

**Describe the bug**
When I define a tensor with the torch backend, it works fine and by printing it, it indicates that it's located on the cpu, which is fine. However when I try to move it to the GPU I get the following error (I cut it for readability) :
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Torch("Could not run 'aten::empty_strided' with arguments from the
 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build 
process (if using custom build). 
[..]
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/result.rs:1076:23
   4: tch::wrappers::tensor_generated::<impl tch::wrappers::tensor::Tensor>::to
             at /home/luis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tch-0.13.0/src/wrappers/tensor_generated.rs:17243:9
   5: burn_tch::ops::tensor::<impl burn_tensor::tensor::ops::tensor::TensorOps<burn_tch::backend::TchBackend<E>> for burn_tch::backend::TchBackend<E>>::to_device
             at /home/luis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/burn-tch-0.9.0/src/ops/tensor.rs:103:24
   6: <burn_tensor::tensor::api::kind::Float as burn_tensor::tensor::api::base::BasicOps<B>>::to_device
             at /home/luis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/burn-tensor-0.9.0/src/tensor/api/base.rs:845:9
   7: burn_tensor::tensor::api::base::Tensor<B,_,K>::to_device
             at /home/luis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/burn-tensor-0.9.0/src/tensor/api/base.rs:292:19
   8: burn_app::main
             at ./src/main.rs:7:16
   9: core::ops::function::FnOnce::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/ops/function.rs:250:5
```
From the error description, I think is some kind of bug, but it will be nice to know if I am doing something wrong.

**To Reproduce**
This is a minimalistic code to reproduce the issue:
```rust
use burn::backend::tch::{TchBackend, TchDevice};
use burn::tensor::Tensor;
fn main() {
    type MyBackend = TchBackend<f32>;
    
    let mut tensor_1 = Tensor::<MyBackend, 2>::from_data([[2., 3.], [4., 5.]]);
    tensor_1 = tensor_1.to_device(&TchDevice::Cuda(0));
    println!("{}", tensor_1)
}
```

**Expected behavior**
The tensor should be moved to the CUDA device

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Rust version: 1.72.1
 - GPU: Nvidia 1660 TI 6 GB
 - Cuda version: 11.6

**Comment by antimora** [comment]
Probably you need to update your cuda to 11.7 since [tch](https://github.com/LaurentMazare/tch-rs) is using Torch 2.0, or your CUDA version is not set correctly. 

Can you try this first?

```
export TORCH_CUDA_VERSION=cu116
```

If not, then you'll have to update your cuda version to 11.7. 

Sorry, it's our fault we do not have a good documentation for setting up Torch backend. We have an outstanding issue ticket for this: https://github.com/burn-rs/burn/issues/587

**Comment by lfsalasg** [comment]
Hi, thanks for the ideas. I tried setting up the `TORCH_CUDA_VERSION` but it didn't work. I would try to check if there is some workaround to either point to a libtorch intallation or to effectively set the proper cuda version.  (I do not really want to update CUDA for now, so this will be my last option)
