### ISSUE TITLE
Use ellipses when pretty printing large tensors (like PyTorch)

### ISSUE THREAD

**Issue by rerz** [burn-rs/burn#850]
### Feature description
When printing tensors in pytorch they use ellipses (...) if a dimensions gets too long. I think the cutoff in pytorch is 10 elements (i.e the 5 starting elements and the 5 last elements).
Currently all tensors are being printed in full.

### Feature motivation
Particularly when printing large tensors, the creation of the string representation takes a long time. Often it is enough to see the first few elements of a tensor to know if it looks the way you want it to.

### (Optional) Suggest a Solution
A user on discord suggested that the implementation could be based off of that of the pretty printing method used in candle that can be found here: https://github.com/huggingface/candle/blob/4631c48273330753c25cf75616ade152915301a2/candle-core/src/display.rs#L3

**Comment by macroexpansion** [comment]
Hi, I want to work on this.

**Comment by antimora** [comment]
@macroexpansion That's great! Please go ahead. If you are stuck or need help you can add your comments here or on discord channel (faster response).

**Comment by agelas** [comment]
@macroexpansion You'll probably need to change the number of elements that are iterated over in `display_recursive` in `burn-tensor/src/tensor/api/base.rs`. It's been like half a year since I did the first implementation so I forget exactly what I did but let me know if you have any questions!
