### ISSUE TITLE
Huggingface::downloader::HuggingfaceDatasetLoader Error

### ISSUE THREAD

**Issue by crazyn2** [burn-rs/burn#913]
**Describe the bug**

in Huggingface::downloader crate, importer.py downloaded files from huggingface and saved it into sqlite3 style. For example, mnist dataset was transferred into byte style in img_byte column of sqlite3. The mnist image is 28*28 size so the byte length should be 784. However, when I loaded the sqlite database and discovered that it's less than 784. After I reviewed the importer.py and mnist.rs, rust code logic is to read image byte from sqlite column but what importer.py wrote is not expected.
In my opinion, it should be transformed into image bytes utilizing Pillow.tobytes function instead of datasets implementation.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by crazyn2** [comment]
My fault.

**Comment by antimora** [comment]
@crazyn2 you can also share your misunderstanding if you'd like for improving documentation or communication.
