### ISSUE TITLE
Training fails to start with checkpoints enabled

### ISSUE THREAD

**Issue by ArvidHammarlund** [burn-rs/burn#934]
**Describe the bug**
Training fails to start when using burn-train with checkpoints enabled - it just hangs, and then quits after a second or so. In the logs the only entries are announcing start of fitting model, and then creation of what I presume Is the log file. 

The problem does not exist when checkpoints are not used.

I'm using /tmp as output dir so permissions should not be a problem.

I'm using the Wgpu backend.

Is this something that others are seeing as well? 

**Desktop (please complete the following information):**
 - OS: Fedora linux

**Comment by nathanielsimard** [comment]
Hmm I'm unsure, can you reproduce the bug with an example?

**Comment by ArvidHammarlund** [comment]
I've got it working now. Was a bug in my own version, and a misinterpretation of the docs.
