### ISSUE TITLE
./run-checks.sh all report 'error: useless use of `format!`' when compiler burn-train

### ISSUE THREAD

**Issue by meteor-lsw** [burn-rs/burn#940]
![image](https://github.com/burn-rs/burn/assets/22556004/39cf09a6-0d51-4e9c-8a38-e57998dee4b7)

Compiling onnx-tests v0.11.0 (/home/lws/projects/burn/burn-import/onnx-tests)
    Checking burn-tch v0.11.0 (/home/lws/projects/burn/burn-tch)
    Checking burn-train v0.11.0 (/home/lws/projects/burn/burn-train)
error: useless use of `format!`
   --> burn-train/src/renderer/tui/progress.rs:193:9
    |
193 |         format!("1 day")
    |         ^^^^^^^^^^^^^^^^ help: consider using `.to_string()`: `"1 day".to_string()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_format
    = note: `-D clippy::useless-format` implied by `-D warnings`

error: useless use of `format!`
   --> burn-train/src/renderer/tui/progress.rs:197:9
    |
197 |         format!("1 hour")
    |         ^^^^^^^^^^^^^^^^^ help: consider using `.to_string()`: `"1 hour".to_string()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_format

error: useless use of `format!`
   --> burn-train/src/renderer/tui/progress.rs:201:9
    |
201 |         format!("1 min")
    |         ^^^^^^^^^^^^^^^^ help: consider using `.to_string()`: `"1 min".to_string()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_format

error: useless use of `format!`
   --> burn-train/src/renderer/tui/progress.rs:205:9
    |
205 |         format!("1 sec")
    |         ^^^^^^^^^^^^^^^^ help: consider using `.to_string()`: `"1 sec".to_string()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_format

error: could not compile `burn-train` (lib) due to 4 previous errors

**Comment by nathanielsimard** [comment]
What is your version of Rust?

**Comment by meteor-lsw** [comment]
I am using current stable rust(1.73)

**Comment by meteor-lsw** [comment]
![image](https://github.com/burn-rs/burn/assets/22556004/c56ccb8c-a342-4803-b816-609cfe5fcebe)

**Comment by meteor-lsw** [comment]
Do you suggest that I submit a small PR for this issue to be fixed? If you do, I would be happy to use this small issue as a starting point to try to contribute.

**Comment by meteor-lsw** [comment]
I found that the problem in the latest code has been fixed, so I close this issue
